name: NCTMOBILE CD

on:
  push:
    branches:
      - main
      - secondB

  pull_request:
    branches:
      - main
      - secondB

jobs:
  deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windowns-latest", "macOs-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up code
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: install dependenices
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy a;plication
        run: |
          echo "Deployment completed"
